/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BadRequestByIdErrorResponse,
  GetAllPracticeParams,
  PermissionDeniedErrorResponse,
  PostCreatePracticeBody,
  Practice,
  PutUpdatePracticeBody,
  UnauthorizedErrorResponse,
} from ".././model";

import { customInstance } from "../../lib/axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Create one practice item
 * @summary Create one practice item
 */
export const postCreatePractice = (
  discipline: string,
  postCreatePracticeBody: PostCreatePracticeBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Practice>(
    {
      url: `/${discipline}/practice`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postCreatePracticeBody,
      signal,
    },
    options,
  );
};

export const getPostCreatePracticeMutationOptions = <
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCreatePractice>>,
    TError,
    { discipline: string; data: PostCreatePracticeBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCreatePractice>>,
  TError,
  { discipline: string; data: PostCreatePracticeBody },
  TContext
> => {
  const mutationKey = ["postCreatePractice"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCreatePractice>>,
    { discipline: string; data: PostCreatePracticeBody }
  > = (props) => {
    const { discipline, data } = props ?? {};

    return postCreatePractice(discipline, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCreatePracticeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCreatePractice>>
>;
export type PostCreatePracticeMutationBody = PostCreatePracticeBody;
export type PostCreatePracticeMutationError =
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Create one practice item
 */
export const usePostCreatePractice = <
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCreatePractice>>,
      TError,
      { discipline: string; data: PostCreatePracticeBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postCreatePractice>>,
  TError,
  { discipline: string; data: PostCreatePracticeBody },
  TContext
> => {
  const mutationOptions = getPostCreatePracticeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get the full list of practice tasks, using pagination
 * @summary Get the full list of practice tasks
 */
export const getAllPractice = (
  discipline: string,
  params?: GetAllPracticeParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Practice[]>(
    { url: `/${discipline}/practice`, method: "GET", params, signal },
    options,
  );
};

export const getGetAllPracticeQueryKey = (
  discipline: string,
  params?: GetAllPracticeParams,
) => {
  return [`/${discipline}/practice`, ...(params ? [params] : [])] as const;
};

export const getGetAllPracticeQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllPractice>>,
  TError = unknown,
>(
  discipline: string,
  params?: GetAllPracticeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllPractice>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAllPracticeQueryKey(discipline, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllPractice>>> = ({
    signal,
  }) => getAllPractice(discipline, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!discipline,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllPractice>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetAllPracticeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllPractice>>
>;
export type GetAllPracticeQueryError = unknown;

export function useGetAllPractice<
  TData = Awaited<ReturnType<typeof getAllPractice>>,
  TError = unknown,
>(
  discipline: string,
  params: undefined | GetAllPracticeParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllPractice>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllPractice>>,
          TError,
          Awaited<ReturnType<typeof getAllPractice>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetAllPractice<
  TData = Awaited<ReturnType<typeof getAllPractice>>,
  TError = unknown,
>(
  discipline: string,
  params?: GetAllPracticeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllPractice>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllPractice>>,
          TError,
          Awaited<ReturnType<typeof getAllPractice>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetAllPractice<
  TData = Awaited<ReturnType<typeof getAllPractice>>,
  TError = unknown,
>(
  discipline: string,
  params?: GetAllPracticeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllPractice>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get the full list of practice tasks
 */

export function useGetAllPractice<
  TData = Awaited<ReturnType<typeof getAllPractice>>,
  TError = unknown,
>(
  discipline: string,
  params?: GetAllPracticeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllPractice>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetAllPracticeQueryOptions(
    discipline,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Delete an existing practice item
 * @summary Delete an existing practice item
 */
export const deletePractice = (
  discipline: string,
  practiceId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/${discipline}/practice/${practiceId}`, method: "DELETE" },
    options,
  );
};

export const getDeletePracticeMutationOptions = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePractice>>,
    TError,
    { discipline: string; practiceId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePractice>>,
  TError,
  { discipline: string; practiceId: string },
  TContext
> => {
  const mutationKey = ["deletePractice"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePractice>>,
    { discipline: string; practiceId: string }
  > = (props) => {
    const { discipline, practiceId } = props ?? {};

    return deletePractice(discipline, practiceId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePracticeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePractice>>
>;

export type DeletePracticeMutationError =
  | BadRequestByIdErrorResponse
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Delete an existing practice item
 */
export const useDeletePractice = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePractice>>,
      TError,
      { discipline: string; practiceId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePractice>>,
  TError,
  { discipline: string; practiceId: string },
  TContext
> => {
  const mutationOptions = getDeletePracticeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Update an existing practice item
 * @summary Update an existing practice item
 */
export const putUpdatePractice = (
  discipline: string,
  practiceId: string,
  putUpdatePracticeBody: PutUpdatePracticeBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<Practice>(
    {
      url: `/${discipline}/practice/${practiceId}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: putUpdatePracticeBody,
    },
    options,
  );
};

export const getPutUpdatePracticeMutationOptions = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putUpdatePractice>>,
    TError,
    { discipline: string; practiceId: string; data: PutUpdatePracticeBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putUpdatePractice>>,
  TError,
  { discipline: string; practiceId: string; data: PutUpdatePracticeBody },
  TContext
> => {
  const mutationKey = ["putUpdatePractice"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putUpdatePractice>>,
    { discipline: string; practiceId: string; data: PutUpdatePracticeBody }
  > = (props) => {
    const { discipline, practiceId, data } = props ?? {};

    return putUpdatePractice(discipline, practiceId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutUpdatePracticeMutationResult = NonNullable<
  Awaited<ReturnType<typeof putUpdatePractice>>
>;
export type PutUpdatePracticeMutationBody = PutUpdatePracticeBody;
export type PutUpdatePracticeMutationError =
  | BadRequestByIdErrorResponse
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Update an existing practice item
 */
export const usePutUpdatePractice = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putUpdatePractice>>,
      TError,
      { discipline: string; practiceId: string; data: PutUpdatePracticeBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putUpdatePractice>>,
  TError,
  { discipline: string; practiceId: string; data: PutUpdatePracticeBody },
  TContext
> => {
  const mutationOptions = getPutUpdatePracticeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get a certain practice task by practice_id
 * @summary Get a certain practice task by practice_id
 */
export const getOnePractice = (
  discipline: string,
  practiceId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Practice>(
    { url: `/${discipline}/practice/${practiceId}`, method: "GET", signal },
    options,
  );
};

export const getGetOnePracticeQueryKey = (
  discipline: string,
  practiceId: string,
) => {
  return [`/${discipline}/practice/${practiceId}`] as const;
};

export const getGetOnePracticeQueryOptions = <
  TData = Awaited<ReturnType<typeof getOnePractice>>,
  TError = void,
>(
  discipline: string,
  practiceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOnePractice>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOnePracticeQueryKey(discipline, practiceId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOnePractice>>> = ({
    signal,
  }) => getOnePractice(discipline, practiceId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(discipline && practiceId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOnePractice>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetOnePracticeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOnePractice>>
>;
export type GetOnePracticeQueryError = void;

export function useGetOnePractice<
  TData = Awaited<ReturnType<typeof getOnePractice>>,
  TError = void,
>(
  discipline: string,
  practiceId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOnePractice>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOnePractice>>,
          TError,
          Awaited<ReturnType<typeof getOnePractice>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetOnePractice<
  TData = Awaited<ReturnType<typeof getOnePractice>>,
  TError = void,
>(
  discipline: string,
  practiceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOnePractice>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOnePractice>>,
          TError,
          Awaited<ReturnType<typeof getOnePractice>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetOnePractice<
  TData = Awaited<ReturnType<typeof getOnePractice>>,
  TError = void,
>(
  discipline: string,
  practiceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOnePractice>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get a certain practice task by practice_id
 */

export function useGetOnePractice<
  TData = Awaited<ReturnType<typeof getOnePractice>>,
  TError = void,
>(
  discipline: string,
  practiceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOnePractice>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetOnePracticeQueryOptions(
    discipline,
    practiceId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
