/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BadRequestByIdErrorResponse,
  Discipline,
  PermissionDeniedErrorResponse,
  PostCreateDisciplineBody,
  UnauthorizedErrorResponse,
  UpdateDisciplineBody,
} from ".././model";

import { customInstance } from "../../lib/axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get all existing disciplines
 * @summary Get all existing disciplines
 */
export const getDisciplines = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Discipline[]>(
    { url: `/disciplines/get-all`, method: "GET", signal },
    options,
  );
};

export const getGetDisciplinesQueryKey = () => {
  return [`/disciplines/get-all`] as const;
};

export const getGetDisciplinesQueryOptions = <
  TData = Awaited<ReturnType<typeof getDisciplines>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getDisciplines>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDisciplinesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDisciplines>>> = ({
    signal,
  }) => getDisciplines(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDisciplines>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetDisciplinesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDisciplines>>
>;
export type GetDisciplinesQueryError =
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

export function useGetDisciplines<
  TData = Awaited<ReturnType<typeof getDisciplines>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDisciplines>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDisciplines>>,
          TError,
          Awaited<ReturnType<typeof getDisciplines>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetDisciplines<
  TData = Awaited<ReturnType<typeof getDisciplines>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDisciplines>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDisciplines>>,
          TError,
          Awaited<ReturnType<typeof getDisciplines>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetDisciplines<
  TData = Awaited<ReturnType<typeof getDisciplines>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDisciplines>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get all existing disciplines
 */

export function useGetDisciplines<
  TData = Awaited<ReturnType<typeof getDisciplines>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDisciplines>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetDisciplinesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Create a new discipline
 * @summary Create a new discipline
 */
export const postCreateDiscipline = (
  postCreateDisciplineBody: PostCreateDisciplineBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Discipline>(
    {
      url: `/disciplines`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postCreateDisciplineBody,
      signal,
    },
    options,
  );
};

export const getPostCreateDisciplineMutationOptions = <
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCreateDiscipline>>,
    TError,
    { data: PostCreateDisciplineBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCreateDiscipline>>,
  TError,
  { data: PostCreateDisciplineBody },
  TContext
> => {
  const mutationKey = ["postCreateDiscipline"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCreateDiscipline>>,
    { data: PostCreateDisciplineBody }
  > = (props) => {
    const { data } = props ?? {};

    return postCreateDiscipline(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCreateDisciplineMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCreateDiscipline>>
>;
export type PostCreateDisciplineMutationBody = PostCreateDisciplineBody;
export type PostCreateDisciplineMutationError =
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Create a new discipline
 */
export const usePostCreateDiscipline = <
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCreateDiscipline>>,
      TError,
      { data: PostCreateDisciplineBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postCreateDiscipline>>,
  TError,
  { data: PostCreateDisciplineBody },
  TContext
> => {
  const mutationOptions = getPostCreateDisciplineMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Delete a certain discipline
 * @summary Delete a certain discipline
 */
export const deleteDiscipline = (
  disciplineId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/disciplines/${disciplineId}`, method: "DELETE" },
    options,
  );
};

export const getDeleteDisciplineMutationOptions = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDiscipline>>,
    TError,
    { disciplineId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteDiscipline>>,
  TError,
  { disciplineId: string },
  TContext
> => {
  const mutationKey = ["deleteDiscipline"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteDiscipline>>,
    { disciplineId: string }
  > = (props) => {
    const { disciplineId } = props ?? {};

    return deleteDiscipline(disciplineId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteDisciplineMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteDiscipline>>
>;

export type DeleteDisciplineMutationError =
  | BadRequestByIdErrorResponse
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Delete a certain discipline
 */
export const useDeleteDiscipline = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteDiscipline>>,
      TError,
      { disciplineId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteDiscipline>>,
  TError,
  { disciplineId: string },
  TContext
> => {
  const mutationOptions = getDeleteDisciplineMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Update an existing discipline
 * @summary Update an existing discipline
 */
export const updateDiscipline = (
  disciplineId: string,
  updateDisciplineBody: UpdateDisciplineBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<Discipline>(
    {
      url: `/disciplines/${disciplineId}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateDisciplineBody,
    },
    options,
  );
};

export const getUpdateDisciplineMutationOptions = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateDiscipline>>,
    TError,
    { disciplineId: string; data: UpdateDisciplineBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateDiscipline>>,
  TError,
  { disciplineId: string; data: UpdateDisciplineBody },
  TContext
> => {
  const mutationKey = ["updateDiscipline"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateDiscipline>>,
    { disciplineId: string; data: UpdateDisciplineBody }
  > = (props) => {
    const { disciplineId, data } = props ?? {};

    return updateDiscipline(disciplineId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateDisciplineMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateDiscipline>>
>;
export type UpdateDisciplineMutationBody = UpdateDisciplineBody;
export type UpdateDisciplineMutationError =
  | BadRequestByIdErrorResponse
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Update an existing discipline
 */
export const useUpdateDiscipline = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateDiscipline>>,
      TError,
      { disciplineId: string; data: UpdateDisciplineBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateDiscipline>>,
  TError,
  { disciplineId: string; data: UpdateDisciplineBody },
  TContext
> => {
  const mutationOptions = getUpdateDisciplineMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
