/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BadRequestByIdErrorResponse,
  PermissionDeniedErrorResponse,
  UnauthorizedErrorResponse,
  UpdateUserBody,
  UpdateUserRoleBody,
  User,
} from ".././model";

import { customInstance } from "../../lib/axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get a list of all existing users
 * @summary Get a list of all existing users
 */
export const getUsersList = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<User[]>(
    { url: `/user/get-all`, method: "GET", signal },
    options,
  );
};

export const getGetUsersListQueryKey = () => {
  return [`/user/get-all`] as const;
};

export const getGetUsersListQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsersList>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersList>>> = ({
    signal,
  }) => getUsersList(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUsersList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetUsersListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsersList>>
>;
export type GetUsersListQueryError =
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

export function useGetUsersList<
  TData = Awaited<ReturnType<typeof getUsersList>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersList>>,
          TError,
          Awaited<ReturnType<typeof getUsersList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetUsersList<
  TData = Awaited<ReturnType<typeof getUsersList>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersList>>,
          TError,
          Awaited<ReturnType<typeof getUsersList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetUsersList<
  TData = Awaited<ReturnType<typeof getUsersList>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get a list of all existing users
 */

export function useGetUsersList<
  TData = Awaited<ReturnType<typeof getUsersList>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetUsersListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get data of certain user by given id
 * @summary Get data of certain user by given id
 */
export const getUsersById = (
  userId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<User[]>(
    { url: `/user/${userId}`, method: "GET", signal },
    options,
  );
};

export const getGetUsersByIdQueryKey = (userId: string) => {
  return [`/user/${userId}`] as const;
};

export const getGetUsersByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsersById>>,
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersById>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersByIdQueryKey(userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersById>>> = ({
    signal,
  }) => getUsersById(userId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUsersById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetUsersByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsersById>>
>;
export type GetUsersByIdQueryError =
  | BadRequestByIdErrorResponse
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

export function useGetUsersById<
  TData = Awaited<ReturnType<typeof getUsersById>>,
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
>(
  userId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersById>>,
          TError,
          Awaited<ReturnType<typeof getUsersById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetUsersById<
  TData = Awaited<ReturnType<typeof getUsersById>>,
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersById>>,
          TError,
          Awaited<ReturnType<typeof getUsersById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetUsersById<
  TData = Awaited<ReturnType<typeof getUsersById>>,
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersById>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get data of certain user by given id
 */

export function useGetUsersById<
  TData = Awaited<ReturnType<typeof getUsersById>>,
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersById>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetUsersByIdQueryOptions(userId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Delete an existing user by given id
 * @summary Delete an existing user by given id
 */
export const deleteUser = (
  userId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/user/delete-user/${userId}`, method: "DELETE" },
    options,
  );
};

export const getDeleteUserMutationOptions = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    { userId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { userId: string },
  TContext
> => {
  const mutationKey = ["deleteUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUser>>,
    { userId: string }
  > = (props) => {
    const { userId } = props ?? {};

    return deleteUser(userId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUser>>
>;

export type DeleteUserMutationError =
  | BadRequestByIdErrorResponse
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Delete an existing user by given id
 */
export const useDeleteUser = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUser>>,
      TError,
      { userId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { userId: string },
  TContext
> => {
  const mutationOptions = getDeleteUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Update an existing user by given id
 * @summary Update an existing user by given id
 */
export const updateUser = (
  userId: string,
  updateUserBody: UpdateUserBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<User>(
    {
      url: `/user/update-user/${userId}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateUserBody,
    },
    options,
  );
};

export const getUpdateUserMutationOptions = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    { userId: string; data: UpdateUserBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { userId: string; data: UpdateUserBody },
  TContext
> => {
  const mutationKey = ["updateUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUser>>,
    { userId: string; data: UpdateUserBody }
  > = (props) => {
    const { userId, data } = props ?? {};

    return updateUser(userId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUser>>
>;
export type UpdateUserMutationBody = UpdateUserBody;
export type UpdateUserMutationError =
  | BadRequestByIdErrorResponse
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Update an existing user by given id
 */
export const useUpdateUser = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUser>>,
      TError,
      { userId: string; data: UpdateUserBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { userId: string; data: UpdateUserBody },
  TContext
> => {
  const mutationOptions = getUpdateUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Update role in the existing user by given id
 * @summary Update role in the existing user by given id
 */
export const updateUserRole = (
  userId: string,
  updateUserRoleBody: UpdateUserRoleBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<User>(
    {
      url: `/user/update-role/${userId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateUserRoleBody,
    },
    options,
  );
};

export const getUpdateUserRoleMutationOptions = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserRole>>,
    TError,
    { userId: string; data: UpdateUserRoleBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserRole>>,
  TError,
  { userId: string; data: UpdateUserRoleBody },
  TContext
> => {
  const mutationKey = ["updateUserRole"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserRole>>,
    { userId: string; data: UpdateUserRoleBody }
  > = (props) => {
    const { userId, data } = props ?? {};

    return updateUserRole(userId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserRoleMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserRole>>
>;
export type UpdateUserRoleMutationBody = UpdateUserRoleBody;
export type UpdateUserRoleMutationError =
  | BadRequestByIdErrorResponse
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Update role in the existing user by given id
 */
export const useUpdateUserRole = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserRole>>,
      TError,
      { userId: string; data: UpdateUserRoleBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserRole>>,
  TError,
  { userId: string; data: UpdateUserRoleBody },
  TContext
> => {
  const mutationOptions = getUpdateUserRoleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
