/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  AuthResponse,
  PermissionDeniedErrorResponse,
  PostAuthLoginBody,
  PostAuthSignUpBody,
  UnauthorizedErrorResponse,
  UserResponse,
} from ".././model";

import { customInstance } from "../../lib/axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary User login
 */
export const postAuthLogin = (
  postAuthLoginBody: PostAuthLoginBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AuthResponse>(
    {
      url: `/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postAuthLoginBody,
      signal,
    },
    options,
  );
};

export const getPostAuthLoginMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLogin>>,
    TError,
    { data: PostAuthLoginBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data: PostAuthLoginBody },
  TContext
> => {
  const mutationKey = ["postAuthLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthLogin>>,
    { data: PostAuthLoginBody }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthLogin>>
>;
export type PostAuthLoginMutationBody = PostAuthLoginBody;
export type PostAuthLoginMutationError = void;

/**
 * @summary User login
 */
export const usePostAuthLogin = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthLogin>>,
      TError,
      { data: PostAuthLoginBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data: PostAuthLoginBody },
  TContext
> => {
  const mutationOptions = getPostAuthLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Refresh user's token
 */
export const postAuthRefreshToken = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AuthResponse>(
    { url: `/auth/refresh-token`, method: "POST", signal },
    options,
  );
};

export const getPostAuthRefreshTokenMutationOptions = <
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRefreshToken>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthRefreshToken>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["postAuthRefreshToken"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthRefreshToken>>,
    void
  > = () => {
    return postAuthRefreshToken(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthRefreshTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRefreshToken>>
>;

export type PostAuthRefreshTokenMutationError =
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Refresh user's token
 */
export const usePostAuthRefreshToken = <
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthRefreshToken>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthRefreshToken>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getPostAuthRefreshTokenMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Create a new user
 */
export const postAuthSignUp = (
  postAuthSignUpBody: PostAuthSignUpBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UserResponse>(
    {
      url: `/auth/sign-up`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postAuthSignUpBody,
      signal,
    },
    options,
  );
};

export const getPostAuthSignUpMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthSignUp>>,
    TError,
    { data: PostAuthSignUpBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthSignUp>>,
  TError,
  { data: PostAuthSignUpBody },
  TContext
> => {
  const mutationKey = ["postAuthSignUp"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthSignUp>>,
    { data: PostAuthSignUpBody }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthSignUp(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthSignUpMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthSignUp>>
>;
export type PostAuthSignUpMutationBody = PostAuthSignUpBody;
export type PostAuthSignUpMutationError = void;

/**
 * @summary Create a new user
 */
export const usePostAuthSignUp = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthSignUp>>,
      TError,
      { data: PostAuthSignUpBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthSignUp>>,
  TError,
  { data: PostAuthSignUpBody },
  TContext
> => {
  const mutationOptions = getPostAuthSignUpMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
