/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BadRequestByIdErrorResponse,
  CreatePostQuizBody,
  GetAllQuizzes200,
  GetAllQuizzesParams,
  PermissionDeniedErrorResponse,
  Quiz,
  UnauthorizedErrorResponse,
} from ".././model";

import { customInstance } from "../../lib/axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get a list of quizzes for the current user and certain discipline
 * @summary Get a list of quizzes
 */
export const getAllQuizzes = (
  discipline: string,
  params?: GetAllQuizzesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetAllQuizzes200>(
    { url: `/${discipline}/quiz`, method: "GET", params, signal },
    options,
  );
};

export const getGetAllQuizzesQueryKey = (
  discipline: string,
  params?: GetAllQuizzesParams,
) => {
  return [`/${discipline}/quiz`, ...(params ? [params] : [])] as const;
};

export const getGetAllQuizzesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllQuizzes>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  discipline: string,
  params?: GetAllQuizzesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAllQuizzesQueryKey(discipline, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllQuizzes>>> = ({
    signal,
  }) => getAllQuizzes(discipline, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!discipline,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllQuizzes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetAllQuizzesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllQuizzes>>
>;
export type GetAllQuizzesQueryError =
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

export function useGetAllQuizzes<
  TData = Awaited<ReturnType<typeof getAllQuizzes>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  discipline: string,
  params: undefined | GetAllQuizzesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllQuizzes>>,
          TError,
          Awaited<ReturnType<typeof getAllQuizzes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetAllQuizzes<
  TData = Awaited<ReturnType<typeof getAllQuizzes>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  discipline: string,
  params?: GetAllQuizzesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllQuizzes>>,
          TError,
          Awaited<ReturnType<typeof getAllQuizzes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetAllQuizzes<
  TData = Awaited<ReturnType<typeof getAllQuizzes>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  discipline: string,
  params?: GetAllQuizzesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get a list of quizzes
 */

export function useGetAllQuizzes<
  TData = Awaited<ReturnType<typeof getAllQuizzes>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  discipline: string,
  params?: GetAllQuizzesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllQuizzes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetAllQuizzesQueryOptions(
    discipline,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * The new created quiz with tasks and questions will be returned
 * @summary Create a new quiz
 */
export const createPostQuiz = (
  discipline: string,
  createPostQuizBody: CreatePostQuizBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Quiz>(
    {
      url: `/${discipline}/quiz`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createPostQuizBody,
      signal,
    },
    options,
  );
};

export const getCreatePostQuizMutationOptions = <
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPostQuiz>>,
    TError,
    { discipline: string; data: CreatePostQuizBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPostQuiz>>,
  TError,
  { discipline: string; data: CreatePostQuizBody },
  TContext
> => {
  const mutationKey = ["createPostQuiz"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPostQuiz>>,
    { discipline: string; data: CreatePostQuizBody }
  > = (props) => {
    const { discipline, data } = props ?? {};

    return createPostQuiz(discipline, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePostQuizMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPostQuiz>>
>;
export type CreatePostQuizMutationBody = CreatePostQuizBody;
export type CreatePostQuizMutationError =
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Create a new quiz
 */
export const useCreatePostQuiz = <
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPostQuiz>>,
      TError,
      { discipline: string; data: CreatePostQuizBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPostQuiz>>,
  TError,
  { discipline: string; data: CreatePostQuizBody },
  TContext
> => {
  const mutationOptions = getCreatePostQuizMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get a certain quiz item by provided id
 * @summary Get one quiz item
 */
export const getQuiz = (
  discipline: string,
  quizId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Quiz>(
    { url: `/${discipline}/quiz/${quizId}`, method: "GET", signal },
    options,
  );
};

export const getGetQuizQueryKey = (discipline: string, quizId: string) => {
  return [`/${discipline}/quiz/${quizId}`] as const;
};

export const getGetQuizQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuiz>>,
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
>(
  discipline: string,
  quizId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuiz>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetQuizQueryKey(discipline, quizId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuiz>>> = ({
    signal,
  }) => getQuiz(discipline, quizId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(discipline && quizId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getQuiz>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData>;
  };
};

export type GetQuizQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuiz>>
>;
export type GetQuizQueryError =
  | BadRequestByIdErrorResponse
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

export function useGetQuiz<
  TData = Awaited<ReturnType<typeof getQuiz>>,
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
>(
  discipline: string,
  quizId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuiz>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuiz>>,
          TError,
          Awaited<ReturnType<typeof getQuiz>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetQuiz<
  TData = Awaited<ReturnType<typeof getQuiz>>,
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
>(
  discipline: string,
  quizId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuiz>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuiz>>,
          TError,
          Awaited<ReturnType<typeof getQuiz>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetQuiz<
  TData = Awaited<ReturnType<typeof getQuiz>>,
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
>(
  discipline: string,
  quizId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuiz>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get one quiz item
 */

export function useGetQuiz<
  TData = Awaited<ReturnType<typeof getQuiz>>,
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
>(
  discipline: string,
  quizId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getQuiz>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetQuizQueryOptions(discipline, quizId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * One existing quiz will be deleted
 * @summary Delete an existing quiz
 */
export const updatePatchQuiz = (
  discipline: string,
  quizId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/${discipline}/quiz/${quizId}`, method: "DELETE" },
    options,
  );
};

export const getUpdatePatchQuizMutationOptions = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePatchQuiz>>,
    TError,
    { discipline: string; quizId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePatchQuiz>>,
  TError,
  { discipline: string; quizId: string },
  TContext
> => {
  const mutationKey = ["updatePatchQuiz"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePatchQuiz>>,
    { discipline: string; quizId: string }
  > = (props) => {
    const { discipline, quizId } = props ?? {};

    return updatePatchQuiz(discipline, quizId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdatePatchQuizMutationResult = NonNullable<
  Awaited<ReturnType<typeof updatePatchQuiz>>
>;

export type UpdatePatchQuizMutationError =
  | BadRequestByIdErrorResponse
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Delete an existing quiz
 */
export const useUpdatePatchQuiz = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePatchQuiz>>,
      TError,
      { discipline: string; quizId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updatePatchQuiz>>,
  TError,
  { discipline: string; quizId: string },
  TContext
> => {
  const mutationOptions = getUpdatePatchQuizMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
