/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BadRequestByIdErrorResponse,
  DisciplineNotFoundErrorResponse,
  GetAllTheory200,
  GetAllTheoryParams,
  PermissionDeniedErrorResponse,
  PostCreateTheoryBody,
  PutUpdateTheoryBody,
  Theory,
  UnauthorizedErrorResponse,
} from ".././model";

import { customInstance } from "../../lib/axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Create one theory item
 * @summary Create one theory item
 */
export const postCreateTheory = (
  discipline: string,
  postCreateTheoryBody: PostCreateTheoryBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Theory>(
    {
      url: `/${discipline}/theory`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postCreateTheoryBody,
      signal,
    },
    options,
  );
};

export const getPostCreateTheoryMutationOptions = <
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCreateTheory>>,
    TError,
    { discipline: string; data: PostCreateTheoryBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCreateTheory>>,
  TError,
  { discipline: string; data: PostCreateTheoryBody },
  TContext
> => {
  const mutationKey = ["postCreateTheory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCreateTheory>>,
    { discipline: string; data: PostCreateTheoryBody }
  > = (props) => {
    const { discipline, data } = props ?? {};

    return postCreateTheory(discipline, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCreateTheoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCreateTheory>>
>;
export type PostCreateTheoryMutationBody = PostCreateTheoryBody;
export type PostCreateTheoryMutationError =
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Create one theory item
 */
export const usePostCreateTheory = <
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCreateTheory>>,
      TError,
      { discipline: string; data: PostCreateTheoryBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postCreateTheory>>,
  TError,
  { discipline: string; data: PostCreateTheoryBody },
  TContext
> => {
  const mutationOptions = getPostCreateTheoryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get all theory materials, using pagination
 * @summary Get the full list of theory materials
 */
export const getAllTheory = (
  discipline: string,
  params?: GetAllTheoryParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetAllTheory200>(
    { url: `/${discipline}/theory`, method: "GET", params, signal },
    options,
  );
};

export const getGetAllTheoryQueryKey = (
  discipline: string,
  params?: GetAllTheoryParams,
) => {
  return [`/${discipline}/theory`, ...(params ? [params] : [])] as const;
};

export const getGetAllTheoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllTheory>>,
  TError = DisciplineNotFoundErrorResponse,
>(
  discipline: string,
  params?: GetAllTheoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllTheory>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAllTheoryQueryKey(discipline, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllTheory>>> = ({
    signal,
  }) => getAllTheory(discipline, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!discipline,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllTheory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetAllTheoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllTheory>>
>;
export type GetAllTheoryQueryError = DisciplineNotFoundErrorResponse;

export function useGetAllTheory<
  TData = Awaited<ReturnType<typeof getAllTheory>>,
  TError = DisciplineNotFoundErrorResponse,
>(
  discipline: string,
  params: undefined | GetAllTheoryParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllTheory>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllTheory>>,
          TError,
          Awaited<ReturnType<typeof getAllTheory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetAllTheory<
  TData = Awaited<ReturnType<typeof getAllTheory>>,
  TError = DisciplineNotFoundErrorResponse,
>(
  discipline: string,
  params?: GetAllTheoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllTheory>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllTheory>>,
          TError,
          Awaited<ReturnType<typeof getAllTheory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetAllTheory<
  TData = Awaited<ReturnType<typeof getAllTheory>>,
  TError = DisciplineNotFoundErrorResponse,
>(
  discipline: string,
  params?: GetAllTheoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllTheory>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get the full list of theory materials
 */

export function useGetAllTheory<
  TData = Awaited<ReturnType<typeof getAllTheory>>,
  TError = DisciplineNotFoundErrorResponse,
>(
  discipline: string,
  params?: GetAllTheoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllTheory>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetAllTheoryQueryOptions(discipline, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Delete one theory item
 * @summary Delete one theory item
 */
export const deleteTheory = (
  discipline: string,
  theoryId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/${discipline}/theory/${theoryId}`, method: "DELETE" },
    options,
  );
};

export const getDeleteTheoryMutationOptions = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTheory>>,
    TError,
    { discipline: string; theoryId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTheory>>,
  TError,
  { discipline: string; theoryId: string },
  TContext
> => {
  const mutationKey = ["deleteTheory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTheory>>,
    { discipline: string; theoryId: string }
  > = (props) => {
    const { discipline, theoryId } = props ?? {};

    return deleteTheory(discipline, theoryId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTheoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTheory>>
>;

export type DeleteTheoryMutationError =
  | BadRequestByIdErrorResponse
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Delete one theory item
 */
export const useDeleteTheory = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteTheory>>,
      TError,
      { discipline: string; theoryId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteTheory>>,
  TError,
  { discipline: string; theoryId: string },
  TContext
> => {
  const mutationOptions = getDeleteTheoryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Update an existing theory item
 * @summary Update an existing theory item
 */
export const putUpdateTheory = (
  discipline: string,
  theoryId: string,
  putUpdateTheoryBody: PutUpdateTheoryBody,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<Theory>(
    {
      url: `/${discipline}/theory/${theoryId}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: putUpdateTheoryBody,
    },
    options,
  );
};

export const getPutUpdateTheoryMutationOptions = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putUpdateTheory>>,
    TError,
    { discipline: string; theoryId: string; data: PutUpdateTheoryBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putUpdateTheory>>,
  TError,
  { discipline: string; theoryId: string; data: PutUpdateTheoryBody },
  TContext
> => {
  const mutationKey = ["putUpdateTheory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putUpdateTheory>>,
    { discipline: string; theoryId: string; data: PutUpdateTheoryBody }
  > = (props) => {
    const { discipline, theoryId, data } = props ?? {};

    return putUpdateTheory(discipline, theoryId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutUpdateTheoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof putUpdateTheory>>
>;
export type PutUpdateTheoryMutationBody = PutUpdateTheoryBody;
export type PutUpdateTheoryMutationError =
  | BadRequestByIdErrorResponse
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Update an existing theory item
 */
export const usePutUpdateTheory = <
  TError =
    | BadRequestByIdErrorResponse
    | UnauthorizedErrorResponse
    | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putUpdateTheory>>,
      TError,
      { discipline: string; theoryId: string; data: PutUpdateTheoryBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putUpdateTheory>>,
  TError,
  { discipline: string; theoryId: string; data: PutUpdateTheoryBody },
  TContext
> => {
  const mutationOptions = getPutUpdateTheoryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get a certain theory material by theory_id
 * @summary Get a certain theory material by theory_id
 */
export const getOneTheory = (
  discipline: string,
  theoryId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Theory>(
    { url: `/${discipline}/theory/${theoryId}`, method: "GET", signal },
    options,
  );
};

export const getGetOneTheoryQueryKey = (
  discipline: string,
  theoryId: string,
) => {
  return [`/${discipline}/theory/${theoryId}`] as const;
};

export const getGetOneTheoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getOneTheory>>,
  TError = BadRequestByIdErrorResponse,
>(
  discipline: string,
  theoryId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneTheory>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOneTheoryQueryKey(discipline, theoryId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneTheory>>> = ({
    signal,
  }) => getOneTheory(discipline, theoryId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(discipline && theoryId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOneTheory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetOneTheoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOneTheory>>
>;
export type GetOneTheoryQueryError = BadRequestByIdErrorResponse;

export function useGetOneTheory<
  TData = Awaited<ReturnType<typeof getOneTheory>>,
  TError = BadRequestByIdErrorResponse,
>(
  discipline: string,
  theoryId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneTheory>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneTheory>>,
          TError,
          Awaited<ReturnType<typeof getOneTheory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetOneTheory<
  TData = Awaited<ReturnType<typeof getOneTheory>>,
  TError = BadRequestByIdErrorResponse,
>(
  discipline: string,
  theoryId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneTheory>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneTheory>>,
          TError,
          Awaited<ReturnType<typeof getOneTheory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetOneTheory<
  TData = Awaited<ReturnType<typeof getOneTheory>>,
  TError = BadRequestByIdErrorResponse,
>(
  discipline: string,
  theoryId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneTheory>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get a certain theory material by theory_id
 */

export function useGetOneTheory<
  TData = Awaited<ReturnType<typeof getOneTheory>>,
  TError = BadRequestByIdErrorResponse,
>(
  discipline: string,
  theoryId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneTheory>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetOneTheoryQueryOptions(
    discipline,
    theoryId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
