/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */

export type GetAllQuizzesParams = {
  /**
   * Maximum limit per page
   */
  limit?: number;
  /**
   * Number of page
   */
  page?: number;
  /**
   * Is it needed to include finished quizzes
   */
  finished_only?: boolean;
};
