/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */

export type PostCreateRoleBody = {
  /** @minLength 2 */
  name: string;
  access_level: number;
};
