/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */
import type { PostCreateTheoryBodyLinksItem } from "./postCreateTheoryBodyLinksItem";
import type { Content } from "./content";

export type PostCreateTheoryBody = {
  title: string;
  links?: PostCreateTheoryBodyLinksItem[];
  /** @minItems 1 */
  content?: Content[];
};
