/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */
import type { PostCreateTheoryBodyLinksItemTitle } from "./postCreateTheoryBodyLinksItemTitle";

export type PostCreateTheoryBodyLinksItem = {
  resource_name: string;
  url: string;
  title: PostCreateTheoryBodyLinksItemTitle;
};
