/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */
import type { User } from "./user";

export interface Practice {
  discipline: string;
  code?: string;
  answers: string[];
  right_answer: number[];
  details?: string;
  created_at?: string;
  created_by: User;
  updated_at?: string;
}
