/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */

export type PutUpdatePracticeBody = {
  /** @minLength 3 */
  code?: string;
  /** @minItems 2 */
  answers: string[];
  right_answer: number[];
  details?: string;
};
