/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */
import type { Practice } from "./practice";
import type { Theory } from "./theory";
import type { QuizAnsweredQuestions } from "./quizAnsweredQuestions";
import type { User } from "./user";

export interface Quiz {
  id: string;
  discipline: string;
  /** @minLength 1 */
  tasks: Practice[];
  questions: Theory[];
  answered_questions: QuizAnsweredQuestions;
  done: boolean;
  created_at: string;
  updated_at: string;
  created_by: User;
}
