/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */
import type { Content } from "./content";
import type { TheoryLinksItem } from "./theoryLinksItem";
import type { User } from "./user";

export interface Theory {
  _id?: string;
  discipline: string;
  title: string;
  /** @minItems 1 */
  content: Content[];
  links?: TheoryLinksItem[];
  created_at?: string;
  created_by: User;
  updated_at?: string;
}
