/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */
import type { RoleTypes } from "./roleTypes";

export interface UserResponse {
  /**
   * @minLength 5
   * @maxLength 100
   */
  user_name: string;
  /** @pattern /^[\w_.]+@([\w-]+\.)+[\w-]{2,4}$/ */
  user_email: string;
  user_role: RoleTypes;
  id: string;
}
