/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Front interview quiz API
 * This is a simple app for preparation for frontend interview based on the OpenAPI 3.0 specification
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  PermissionDeniedErrorResponse,
  PostCreateRoleBody,
  Role,
  UnauthorizedErrorResponse,
} from ".././model";

import { customInstance } from "../../lib/axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get all existing roles
 * @summary Get all existing roles
 */
export const getRoles = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Role[]>(
    { url: `/role/get-all`, method: "GET", signal },
    options,
  );
};

export const getGetRolesQueryKey = () => {
  return [`/role/get-all`] as const;
};

export const getGetRolesQueryOptions = <
  TData = Awaited<ReturnType<typeof getRoles>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRolesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoles>>> = ({
    signal,
  }) => getRoles(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRoles>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetRolesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRoles>>
>;
export type GetRolesQueryError =
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

export function useGetRoles<
  TData = Awaited<ReturnType<typeof getRoles>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoles>>,
          TError,
          Awaited<ReturnType<typeof getRoles>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetRoles<
  TData = Awaited<ReturnType<typeof getRoles>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoles>>,
          TError,
          Awaited<ReturnType<typeof getRoles>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetRoles<
  TData = Awaited<ReturnType<typeof getRoles>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get all existing roles
 */

export function useGetRoles<
  TData = Awaited<ReturnType<typeof getRoles>>,
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetRolesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Delete a certain role by role_id
 * @summary Delete a certain role by role_id
 */
export const deleteRoleById = (
  roleId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/role/${roleId}`, method: "DELETE" },
    options,
  );
};

export const getDeleteRoleByIdMutationOptions = <
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRoleById>>,
    TError,
    { roleId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteRoleById>>,
  TError,
  { roleId: string },
  TContext
> => {
  const mutationKey = ["deleteRoleById"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteRoleById>>,
    { roleId: string }
  > = (props) => {
    const { roleId } = props ?? {};

    return deleteRoleById(roleId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteRoleByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteRoleById>>
>;

export type DeleteRoleByIdMutationError =
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Delete a certain role by role_id
 */
export const useDeleteRoleById = <
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteRoleById>>,
      TError,
      { roleId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteRoleById>>,
  TError,
  { roleId: string },
  TContext
> => {
  const mutationOptions = getDeleteRoleByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Create a new one role
 * @summary Create a new one role
 */
export const postCreateRole = (
  postCreateRoleBody: PostCreateRoleBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Role>(
    {
      url: `/role`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postCreateRoleBody,
      signal,
    },
    options,
  );
};

export const getPostCreateRoleMutationOptions = <
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCreateRole>>,
    TError,
    { data: PostCreateRoleBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCreateRole>>,
  TError,
  { data: PostCreateRoleBody },
  TContext
> => {
  const mutationKey = ["postCreateRole"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCreateRole>>,
    { data: PostCreateRoleBody }
  > = (props) => {
    const { data } = props ?? {};

    return postCreateRole(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCreateRoleMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCreateRole>>
>;
export type PostCreateRoleMutationBody = PostCreateRoleBody;
export type PostCreateRoleMutationError =
  | UnauthorizedErrorResponse
  | PermissionDeniedErrorResponse;

/**
 * @summary Create a new one role
 */
export const usePostCreateRole = <
  TError = UnauthorizedErrorResponse | PermissionDeniedErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCreateRole>>,
      TError,
      { data: PostCreateRoleBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postCreateRole>>,
  TError,
  { data: PostCreateRoleBody },
  TContext
> => {
  const mutationOptions = getPostCreateRoleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
